export interface Doctor{
    FK_ClinicDept_Code: string,
    ClinicDept_BranchId: number,
    ClinicDept_Code: string,
    ClinicDept_Name_En: string,
    ClinicDept_Name_Ar: string,
    ClinicType:any,
    DoctorCode: string,
    DoctorNameAr: string,
    DoctorNameEn: string,
    DoctorCategory: string,
    FK_Branch_ID: number,
    OfficialAddress: string,
    ResAddress: string,
    Phone: string,
    MobileNumber: string,
    Fax: string,
    Email: string,
    Qualification: string,
    SpecializationEn: string,
    SpecializationAr:string,
    Specialization: string,
    Remarks:string,
    MOHNo:string,
    IDNo: string,
    Doc_Alter_Code: string,
    CostNo:string,
    Active: boolean,
    Signature_Img_Name: any,
    Signature_Img: any,
    Fk_User_ID: number,
    FK_Dr_CommisionAccNo: string,
    FK_AccountNo: string,
    DoctorFlag: number,
    BriefSummary: string,
    Doctor_Operation_Value: 0,
    IS_Out: false,
    DoctorGender: string,
    FK_Seller_ID: string,
    Doctor_ClinicDept_Status: true,
    Doctor_ClinicDeptID: number,
    Branch_ID: number,
    Branch_Name: string,
    Branch_Name_Ar: string,
    Org_Name:string,
    Org_Name_Ar: string,
    Long: number,
    Lat:number,
    Distance: number,
    DoctorPic: string,
    AvgRate: number,
    TotalCnt: number,
    IS_TeleMed: boolean,
    Org_ID: number
}