export interface User{
    Patient_Code: string,
    Patient_Code_F: string,
    Patient_Code_M: string,
    Fk_Branch_Id: number,
    Relation: any,
    User_Name: string,
    Patient_Mobile: string,
    Password: any,
    Sex: string,
    Fk_Company_ID: number,
    Confirmed_at: string,
    Patient_BirthDate: string,
    Patient_FirstName_Ar: string,
    Patient_FatherName_Ar: string,
    Patient_MiddleName_Ar: string,
    Patient_LastName_Ar: string,
    Patient_Name_Ar:string,
    Patient_FirstName_En: string,
    Patient_FatherName_En:string,
    Patient_MiddleName_En: string,
    Patient_LastName_En: string,
    Patient_Name_En: string,
    Salt: any,
    CountryCode: string,
    Latitude:any,
    Longitude: any,
    Patient_Phone: any,
    ID_Number: string,
    Email: string,
    Patient_Address: any,
    Patient_ID_Type:any,
    Job_Name: any,
    PlaceOfWork: any,
    Fk_RegisteredUser: any,
    City: any,
    Guardian: any,
    Clinic_knownFrom: number,
    Country: any,
    PatientAlterCode: any,
    Patient_Age_Year: number,
    IMG: string
}